name: .NET Core

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: GitHub Action to Setup GitVersion
      uses: StanleyGoldman/setup-gitversion@v1.0.1
      with:
          gitversion-version: 5.1.1
          run-gitversion: true
    - run: GitVersion /showconfig
      working-directory: $GITHUB_WORKSPACE	
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name : pack
      run: dotnet pack --output nupkgs
    - name : push
      run: dotnet nuget push nupkgs/ha.sdk.nupkg -k oy2mj6efucshmf7nbmeq4e2idfm66frefddqlr4z3wafci
  
