name: .NET Core

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Download GitVersion
      run: wget https://github.com/GitTools/GitVersion/releases/download/5.5.1/gitversion-ubuntu.18.04-x64-5.5.1.tar.gz
    - name: Extract GitVersion
      run: tar -xf gitversion-ubuntu.18.04-x64-5.5.1.tar.gz
    - name: Run GitVersion 
      run: ./gitversion gitversion.yml -updateassemblyinfo AssemblyInfo.cs -ensureassemblyinfo -output buildserver 
    - name : show env
      run:  echo $GitVersion_NuGetVersion 
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name : pack
      run: dotnet pack --output nupkgs /p:Version=$GitVersion_NuGetVersion
    - name : push
      env:
          NugetPushKey: ${{ secrets.NugetPushKey }}
      run: dotnet nuget push nupkgs/ha.sdk.$GitVersion_NuGetVersion.nupkg -k $NugetPushKey
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.NuGetVersion }}
  
